### PR TITLE
add more flags: public_ip autoconfig, prod_mode, logs

### PR DESCRIPTION
**Pull request by hamsterksu**
1. support amazon ec2
2. add prod_mode
3. improve logs conf

### CODE REVIEW

**Comment by hamsterksu** [comment]
hi @deruelle 
i have made a few tests with log level.

sip stack uses log level from **lb-configuration.properties**  it ignores **lb-log4j.xml**

if you remove **gov.nist.javax.sip.LOG_MESSAGE_CONTENT** from _lb-configuration.properties_ you will not get logs at all even if you have INFO in _lb-log4j.xml_

**Comment by deruelle** [comment]
Sorry I think you need to add gov.nist.javax.sip.LOG4J_LOGGER_NAME=gov.nist as well in addition to gov.nist.javax.sip.TRACE_LEVEL=LOG4J
So please try with 

```
gov.nist.javax.sip.LOG_MESSAGE_CONTENT=true
gov.nist.javax.sip.LOG4J_LOGGER_NAME=gov.nist
gov.nist.javax.sip.TRACE_LEVEL=LOG4J
```

This is how we do it in SIP Servlets and RestComm

**Comment by hamsterksu** [comment]
hi @deruelle  
i have updated PR  - not it uses `TRACE_LEVEL=LOG4J`
could you review it please?

**Comment by deruelle** [comment]
@hamsterksu merged. One note on production mode, I think it would be better to be able to override the memory settings via configuration in case someone wants a bigger heap.

**Comment by hamsterksu** [comment]
@deruelle yes, i agree with you

**Comment by deruelle** [comment]
@hamsterksu ok feel free to make another pull request for that then

**Comment by hamsterksu** [comment]
@deruelle - done - https://github.com/RestComm/load-balancer-docker/pull/6

**Pull request merged**
